// Photos for menu items and section banners (client/public/images/menu/photos).
// Free-to-use Unsplash photos; see photos/credits.json for photographers.
// Items/categories that set their own imageUrl in the menu files (e.g. Bâton Rouge's own photos) keep it.

const photo = (key) => `/images/menu/photos/${key}.jpg`
const banner = (key) => `/images/menu/photos/banner-${key}.jpg`

const ITEM_PHOTOS = {
  'baton-rouge': {
    'Cocktail Shrimp': 'shrimp-cocktail',
    'Beef Tartare Bites (12)': 'beef-tartare',
    'Salmon Gravlax Bites (12)': 'gravlax',
    'Asian Tuna Tartare Bites (12)': 'tuna-tartare',
    'Shrimp Tempura (16)': 'tempura',
    'Cauliflower Wings (16)': 'cauliflower',
    'Feta & Spicy Honey Bites (12)': 'feta-honey',
    'Beef Flank Steak Bites (24)': 'steak-bites',
    'Cheesy Garlic Bread Bites (16)': 'garlic-bread',
  },
  'wendel-clarks': {
    'Healthy Start Breakfast': 'yogurt-parfait',
    'Hot Breakfast Buffet': 'french-toast',
    'Breakfast Sandwich': 'breakfast-sandwich',
    'Florentine Breakfast Wrap': 'breakfast-wrap',
    'Spinach Dip': 'spinach-dip',
    'Fresh Pico de Gallo': 'salsa',
    'House Made Guacamole with Tortilla Chips': 'guacamole',
    'Chicken Skewer Collection': 'chicken-skewers',
    'Chicken Wings': 'chicken-wings',
    'Arancini Balls': 'arancini',
    'Bacon Wrapped Peach': 'bacon-wrapped',
    'BBQ Pulled Pork Slider': 'sliders',
    'Spicy Chorizo in Honey Dijon Glaze': 'chorizo',
    'House Made Meatball Collection': 'meatballs',
    'Vegetable and Dip Selection': 'veggie-platter',
    'Fresh Fruit Selection': 'fruit-platter',
    'Domestic & Imported Cheese Selection': 'cheese-board',
    'Meat & Cheese Platter': 'charcuterie',
    'Charcuterie Slab': 'charcuterie',
    'Beef on a Bun': 'roast-beef-sandwich',
    'Wendel Chili': 'chili',
    'Lasagna Meal': 'lasagna',
    'Italian Delight': 'alfredo-pasta',
    'Indian Combo': 'butter-chicken',
    'Crispy Buttermilk Chicken Lunch': 'fried-chicken',
    'Salmon Meal': 'salmon',
    'Grilled Chicken in White Wine Sauce': 'grilled-chicken',
    'Soup, Salad & Sandwich – Classic': 'soup-sandwich',
    'Soup, Salad & Sandwich – Deluxe': 'salad',
    'Cold Canapés': 'canapes',
    'Hot Canapés': 'hors-doeuvres',
    'Classic Poutine': 'poutine',
    'Late Night Bites': 'spring-rolls',
    'Classic Roast Beef Dinner': 'roast-beef',
    'Prime Rib Dinner': 'prime-rib',
    'Traditional Roast Turkey Dinner': 'roast-turkey',
    'Assorted Drinks': 'soft-drinks',
    'San Pellegrino Sparkling Water (330 ml)': 'sparkling-water',
    'Freshly Brewed Coffee / Tea': 'coffee',
    'Non-Alcoholic Cocktail': 'mocktail',
    'House Spirits': 'whiskey',
    'Premium Spirits': 'spirits',
    'Classic Caesar': 'caesar-cocktail',
    'Red or White Wine': 'wine',
    Beer: 'beer',
  },
  'lions-den': {
    'Continental Breakfast': 'pastries',
    'Healthy Breakfast': 'yogurt-parfait',
    'Hot Breakfast – Option 1': 'pancakes',
    'Hot Breakfast – Option 2': 'eggs-bacon',
    'Bacon or Sausage': 'bacon',
    'Individual Yogurts': 'yogurt-parfait',
    'Granola or Cereal Bars': 'granola-bars',
    'Bottled Water': 'bottled-water',
    'Assorted Juices': 'juice',
    'Coffee / Tea Service': 'coffee',
    'Cold Lunch – Choice #1': 'finger-sandwiches',
    'Cold Lunch – Choice #2': 'soup-sandwich',
    'Cold Lunch – Choice #3': 'wraps-platter',
    'Additional Salad': 'salad',
    'Just Sandwiches': 'deli-sandwich',
    'Hot Lunch – Select 1 Main Entrée': 'lasagna',
    'Build Your Own Burger': 'burger',
    'We Do Bar-B-Que': 'bbq-grill',
    'Appetizer Buffet – Pick 3': 'chicken-wings',
    'Appetizer Buffet – Pick 5': 'appetizer-platter',
    'Dinner Buffet': 'roast-beef',
    'Carvery Christmas': 'roast-turkey',
    'Corkage Bar': 'soft-drinks',
    'Beer and Wine Bar': 'wine',
    'Full Service Bar': 'cocktail-bar',
    'Servers / Bussers': 'waiter',
    Bartender: 'bartender',
    'Chef / Carver': 'chef-carving',
    'Custom Menu Request': 'catering-buffet',
  },
  'festive-menu': {
    'Classic Roast Beef Dinner': 'roast-beef',
    'Prime Rib Dinner': 'prime-rib',
    'Traditional Roast Turkey Dinner': 'roast-turkey',
    'Chicken Skewer Collection': 'chicken-skewers',
    'Chicken Wings': 'chicken-wings',
    'Hot Bites Platter': 'appetizer-platter',
    'Charcuterie Slab': 'charcuterie',
    'Cold Canapés': 'canapes',
    'Hot Canapés': 'hors-doeuvres',
    'Late Night Snacks Platter': 'party-food',
    'Late Night Snack Station': 'poutine',
    'Assorted Drinks': 'soft-drinks',
    'San Pellegrino Sparkling Water': 'sparkling-water',
    'Non-Alcoholic Cocktail': 'mocktail',
    'House Spirits': 'whiskey',
    'Premium Spirits': 'spirits',
    'Classic Caesar Drink': 'caesar-cocktail',
    'Red or White Wine': 'wine',
    Beer: 'beer',
  },
}

const CATEGORY_BANNERS = {
  'baton-rouge': {
    'Bites – Cold': 'shrimp-cocktail',
  },
  'wendel-clarks': {
    Breakfast: 'breakfast-buffet',
    Appetizers: 'chicken-skewers',
    'Hot Bites': 'sliders',
    'Platters & Charcuterie': 'charcuterie',
    Lunch: 'butter-chicken',
    'Soup, Salad & Sandwich Lunch': 'soup-sandwich',
    Canapés: 'canapes',
    'Late Night Snacks': 'poutine',
    Dinner: 'prime-rib',
    Beverages: 'mocktail',
    Bar: 'cocktail-bar',
  },
  'lions-den': {
    Breakfast: 'pastries',
    'Breakfast Additions': 'breakfast-buffet',
    'Cold Lunch': 'finger-sandwiches',
    'Hot Lunch': 'lasagna',
    'Appetizer Buffets': 'appetizer-platter',
    'Dinner Buffet': 'roast-beef',
    'Christmas Carvery': 'roast-turkey',
    'Beverage Services': 'soft-drinks',
    'Event Staff': 'waiter',
    'Custom Menu': 'catering-buffet',
  },
  'festive-menu': {
    'Festive Dinners': 'holiday-dinner',
    Appetizers: 'appetizer-platter',
    Canapés: 'canapes',
    'Late Night Snacks': 'party-food',
    Beverages: 'mocktail',
    'Holiday Bar': 'cocktail-bar',
  },
}

export function itemPhoto(slug, itemName) {
  const key = ITEM_PHOTOS[slug]?.[itemName]
  return key ? photo(key) : null
}

export function categoryBanner(slug, categoryName) {
  const key = CATEGORY_BANNERS[slug]?.[categoryName]
  return key ? banner(key) : null
}
